import type {
  Business,
  Plan,
  SupportTicket,
  TicketTrend,
  POSData,
  BusinessSalesData,
  TimeFilter,
} from "@/types/analytics"

export const timeFilters: TimeFilter[] = [
  { label: "Last 7 Days", value: "7d" },
  { label: "Last 30 Days", value: "30d" },
  { label: "Last 90 Days", value: "90d" },
  { label: "This Year", value: "year" },
  { label: "All Time", value: "all" },
]

export const businesses: Business[] = [
  {
    id: "b1",
    name: "Coffee House Downtown",
    email: "info@coffeedowntown.com",
    plan: "premium",
    status: "active",
    onboardedDate: new Date("2023-01-15"),
    lastActive: new Date("2024-05-12"),
  },
  {
    id: "b2",
    name: "Burger Palace",
    email: "contact@burgerpalace.com",
    plan: "basic",
    status: "active",
    onboardedDate: new Date("2023-02-20"),
    lastActive: new Date("2024-05-13"),
  },
  {
    id: "b3",
    name: "Fresh Bakery",
    email: "hello@freshbakery.com",
    plan: "premium",
    status: "active",
    onboardedDate: new Date("2023-03-10"),
    lastActive: new Date("2024-05-10"),
  },
  {
    id: "b4",
    name: "Gourmet Restaurant",
    email: "info@gourmetrestaurant.com",
    plan: "enterprise",
    status: "active",
    onboardedDate: new Date("2023-01-05"),
    lastActive: new Date("2024-05-11"),
  },
  {
    id: "b5",
    name: "Pizza Express",
    email: "orders@pizzaexpress.com",
    plan: "basic",
    status: "inactive",
    onboardedDate: new Date("2023-04-15"),
    lastActive: new Date("2024-03-20"),
  },
  {
    id: "b6",
    name: "Taco Truck",
    email: "hello@tacotruck.com",
    plan: "free",
    status: "inactive",
    onboardedDate: new Date("2023-05-01"),
    lastActive: new Date("2024-02-15"),
  },
  {
    id: "b7",
    name: "Sushi Bar",
    email: "info@sushibar.com",
    plan: "premium",
    status: "active",
    onboardedDate: new Date("2023-02-10"),
    lastActive: new Date("2024-05-12"),
  },
  {
    id: "b8",
    name: "Ice Cream Shop",
    email: "contact@icecreamshop.com",
    plan: "basic",
    status: "active",
    onboardedDate: new Date("2023-03-25"),
    lastActive: new Date("2024-05-09"),
  },
  {
    id: "b9",
    name: "Vegan Cafe",
    email: "hello@vegancafe.com",
    plan: "free",
    status: "pending",
    onboardedDate: new Date("2024-05-01"),
    lastActive: new Date("2024-05-01"),
  },
  {
    id: "b10",
    name: "Steakhouse Grill",
    email: "info@steakhousegrill.com",
    plan: "enterprise",
    status: "active",
    onboardedDate: new Date("2023-01-20"),
    lastActive: new Date("2024-05-13"),
  },
]

export const plans: Plan[] = [
  { type: "free", count: 15, color: "#94A3B8" },
  { type: "basic", count: 42, color: "#60A5FA" },
  { type: "premium", count: 28, color: "#8B5CF6" },
  { type: "enterprise", count: 15, color: "#F97316" },
]

export const tickets: SupportTicket[] = [
  {
    id: "t1",
    businessId: "b1",
    status: "closed",
    priority: "medium",
    category: "billing",
    createdAt: new Date("2024-04-10"),
    resolvedAt: new Date("2024-04-12"),
  },
  {
    id: "t2",
    businessId: "b2",
    status: "open",
    priority: "high",
    category: "technical",
    createdAt: new Date("2024-05-08"),
  },
  {
    id: "t3",
    businessId: "b3",
    status: "pending",
    priority: "low",
    category: "account",
    createdAt: new Date("2024-05-05"),
  },
  {
    id: "t4",
    businessId: "b4",
    status: "closed",
    priority: "medium",
    category: "billing",
    createdAt: new Date("2024-04-20"),
    resolvedAt: new Date("2024-04-22"),
  },
  {
    id: "t5",
    businessId: "b5",
    status: "open",
    priority: "urgent",
    category: "technical",
    createdAt: new Date("2024-05-10"),
  },
  {
    id: "t6",
    businessId: "b1",
    status: "open",
    priority: "high",
    category: "feature",
    createdAt: new Date("2024-05-11"),
  },
  {
    id: "t7",
    businessId: "b7",
    status: "closed",
    priority: "medium",
    category: "billing",
    createdAt: new Date("2024-04-15"),
    resolvedAt: new Date("2024-04-16"),
  },
  {
    id: "t8",
    businessId: "b8",
    status: "closed",
    priority: "low",
    category: "account",
    createdAt: new Date("2024-04-25"),
    resolvedAt: new Date("2024-04-26"),
  },
]

export const ticketTrends: TicketTrend[] = [
  { date: "Jan", open: 12, closed: 10 },
  { date: "Feb", open: 15, closed: 13 },
  { date: "Mar", open: 18, closed: 16 },
  { date: "Apr", open: 22, closed: 19 },
  { date: "May", open: 20, closed: 18 },
  { date: "Jun", open: 25, closed: 22 },
  { date: "Jul", open: 30, closed: 25 },
  { date: "Aug", open: 28, closed: 26 },
  { date: "Sep", open: 24, closed: 23 },
  { date: "Oct", open: 22, closed: 20 },
  { date: "Nov", open: 18, closed: 17 },
  { date: "Dec", open: 16, closed: 15 },
]

export const posData: POSData[] = [
  {
    businessId: "b1",
    businessName: "Coffee House Downtown",
    totalSales: 125000,
    averageOrderValue: 15.75,
    syncFrequency: 24,
    lastSyncDate: new Date("2024-05-13T08:30:00"),
  },
  {
    businessId: "b2",
    businessName: "Burger Palace",
    totalSales: 98500,
    averageOrderValue: 22.5,
    syncFrequency: 12,
    lastSyncDate: new Date("2024-05-13T07:45:00"),
  },
  {
    businessId: "b3",
    businessName: "Fresh Bakery",
    totalSales: 75000,
    averageOrderValue: 18.25,
    syncFrequency: 6,
    lastSyncDate: new Date("2024-05-12T18:30:00"),
  },
  {
    businessId: "b4",
    businessName: "Gourmet Restaurant",
    totalSales: 215000,
    averageOrderValue: 85.5,
    syncFrequency: 4,
    lastSyncDate: new Date("2024-05-13T09:15:00"),
  },
  {
    businessId: "b5",
    businessName: "Pizza Express",
    totalSales: 110000,
    averageOrderValue: 32.75,
    syncFrequency: 8,
    lastSyncDate: new Date("2024-05-12T22:00:00"),
  },
]

export const businessSalesData: BusinessSalesData[] = [
  { businessId: "b1", businessName: "Coffee House Downtown", sales: 125000, transactions: 7937 },
  { businessId: "b2", businessName: "Burger Palace", sales: 98500, transactions: 4378 },
  { businessId: "b3", businessName: "Fresh Bakery", sales: 75000, transactions: 4110 },
  { businessId: "b4", businessName: "Gourmet Restaurant", sales: 215000, transactions: 2515 },
  { businessId: "b5", businessName: "Pizza Express", sales: 110000, transactions: 3359 },
  { businessId: "b7", businessName: "Sushi Bar", sales: 168000, transactions: 3733 },
  { businessId: "b8", businessName: "Ice Cream Shop", sales: 62000, transactions: 5167 },
  { businessId: "b10", businessName: "Steakhouse Grill", sales: 245000, transactions: 2722 },
]
